### ISSUE TITLE
Docker Issues

### ISSUE THREAD

**Issue by ryan-prasanphanich** [joeecarter/health-import-server#1]
Hi, Would you be able to point me in the right direction on resolving this issue?
When I try to run the docker image, I get this error:

panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x57a5ab]

goroutine 1 [running]:

net/url.(*URL).ResolveReference(0x0, 0xc0001642d0, 0xc0001642d0)

	/usr/local/go/src/net/url/url.go:1077 +0x8b

net/url.(*URL).Parse(0x0, 0x86e415, 0x5, 0x8edb00, 0xc00006d3b0, 0x2)

	/usr/local/go/src/net/url/url.go:1065 +0x85

github.com/influxdata/influxdb-client-go/v2/internal/write.NewService(0xc00001ac98, 0x3, 0xc00001aca0, 0x6, 0x8f63e8, 0xc000012700, 0xc000060320, 0xc00001aca6)

	/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.3.0/internal/write/service.go:64 +0xab

github.com/influxdata/influxdb-client-go/v2/api.NewWriteAPIBlocking(...)

	/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.3.0/api/writeAPIBlocking.go:71

github.com/influxdata/influxdb-client-go/v2.(*clientImpl).WriteAPIBlocking(0xc000160180, 0xc00001ac98, 0x3, 0xc00001aca0, 0x6, 0x0, 0x0)

	/go/pkg/mod/github.com/influxdata/influxdb-client-go/v2@v2.3.0/client.go:216 +0x20b

github.com/joeecarter/health-import-server/storage/influxdb.NewInfluxMetricStore(0xc000016108, 0x11, 0xc000062120, 0x58, 0xc00001ac98, 0x3, 0xc00001aca0, 0x6, 0x8)

	/go/src/github.com/joeecarter/health-import-server/storage/influxdb/store.go:26 +0x95

github.com/joeecarter/health-import-server/storage.loadInfluxMetricStore(0xc00015a340, 0xc9, 0xd0, 0x8, 0xc00006f270, 0x1, 0x0)

	/go/src/github.com/joeecarter/health-import-server/storage/load.go:82 +0x11c

github.com/joeecarter/health-import-server/storage.LoadMetricStores(0xc000018011, 0x13, 0xc000018011, 0x13, 0x1)

	/go/src/github.com/joeecarter/health-import-server/storage/load.go:57 +0x27f

main.init.0()

	/go/src/github.com/joeecarter/health-import-server/main.go:27 +0xd5

**Comment by joeecarter** [comment]
Hey @ryan-prasanphanich do you have an example of the docker run command that you executed?

To be honest this project needs a little more polish to make it easier for people to use (and a docker image published). I'll try and revisit it this weekend and get a v1.0.0 published with an example docker-compose file and better docs on how to use it soon.

**Comment by zorrobyte** [comment]
I would love that, I just set up an InfluxDB instance and I hope to aggregate all of my health data into a singular datastore. Then I can start using MQTT and pipe in other sensors, maybe even EEG data (see the Crown EEG) and start to see correlations.

**Comment by joeecarter** [comment]
This is what I think should be done before releasing a v1.0.0 which should easier to run: https://github.com/joeecarter/health-import-server/projects/1

**Comment by joeecarter** [comment]
There is also this board which has some future improvements: https://github.com/joeecarter/health-import-server/projects/2
